# Generated by Django 2.0 on 2018-01-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('result', models.IntegerField()),
                ('transaction', models.IntegerField()),
                ('balance', models.IntegerField()),
            ],
        ),
    ]
