# Generated by Django 2.0 on 2018-01-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='result',
            field=models.BooleanField(),
        ),
    ]
