# Generated by Django 2.0 on 2018-01-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dice', '0002_auto_20180102_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
